addCommandHandler("load",function(player,cmd,mapname) 
    loadmap(player, mapname)
end)
addCommandHandler("mapdim",function(player,cmd,mapname,dim) 
    setMapDimenstion(player, mapname,dim)
end)
addCommandHandler("unloadall",function(player,cmd,mapname) 
    unloadAllMap(player)
end)