function enablePs2Effect()
    enableSunShader()
    enableTrail()
    enableVehiclePipe()
    enableRotorPs2Fix()
    enableBloom()
    enableDiffuse()
end
function disablePs2Effect()
    disableSunShader()
    disableTrail()
    disableVehiclePipe()
    disableRotorPs2Fix()
    disableBloom()
    disableDiffuse()
end
enablePs2Effect()
--enableDiffuse()